version: "3.8"

services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: strapi:prod
    restart: unless-stopped
    env_file: .env.prod
    environment:
      NODE_ENV: production
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/app/package.json
      - ./yarn.lock:/opt/app/yarn.lock
      - ./.env.prod:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
      - ./dump.sql:/opt/app/dump.sql
    ports:
      - "1337:1337"
    depends_on:
      - strapiDB
    networks:
      - strapi

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64
    image: postgres:12.0-alpine
    restart: unless-stopped
    env_file: .env.prod
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data
    ports:
      - "1338:5432"
    networks:
      - strapi

volumes:
  strapi-data:

networks:
  strapi:
    driver: bridge
