FROM node:18-alpine

RUN apk update && apk add --no-cache \
  build-base \
  python3 \
  bash \
  vips-dev \
  git \
  autoconf \
  automake \
  libpng-dev \
  zlib-dev \
  nasm \
  libtool \
  make \
  g++

WORKDIR /opt/app

COPY package*.json ./
RUN npm install

COPY . .
RUN chown -R node:node /opt/app
USER node

RUN rm -rf node_modules/esbuild/bin/* && npm run build

EXPOSE 1337
CMD ["npm", "run", "start"]
